import coachConfig from '../../coach.config'

export const seedHomePage = {
  blocks: [
    {
      blockType: 'homeHeroSection',
      headline: `用 AI 開創你的一人事業`,
      tagline: coachConfig.brand.tagline,
      ctaLabel: coachConfig.cta.primary.label,
      ctaHref: coachConfig.cta.primary.href,
      secondaryCtaLabel: coachConfig.cta.secondary.label,
      secondaryCtaHref: coachConfig.cta.secondary.href,
    },
    {
      blockType: 'levelIntroSection',
      title: '三個階段，從入門到建立系統',
      subtitle: '每個階段都有明確的里程碑，做出真實可用的成果',
      cards: [
        {
          level: 'l1',
          label: 'Level 1',
          name: 'AI 基礎',
          promise: '免費入門課，零基礎開始，做出第一個實際成果',
          ctaLabel: '了解 L1',
          ctaHref: '/pricing',
        },
        {
          level: 'l2',
          label: 'Level 2',
          name: '進階實戰',
          promise: '付費進階課，把技能包裝成可重複銷售的服務或商品',
          ctaLabel: '了解 L2',
          ctaHref: '/pricing',
        },
        {
          level: 'l3',
          label: 'Level 3',
          name: '全面升級',
          promise: '高階完整課，用 AI Agent 建立自動化的一人事業系統',
          ctaLabel: '了解 L3',
          ctaHref: '/pricing',
        },
      ],
    },
    {
      blockType: 'newsletterSignupSection',
      title: '訂閱電子報，第一時間收到最新課程',
      subtitle: '課程開放時，你是第一個知道的人',
      placeholder: '你的 Email',
      buttonLabel: '加入候補名單',
      successMessage: '已加入候補名單，課程開放時將第一時間通知你',
    },
  ],
}

export const seedCourses = [
  {
    title: '[範例] AI 工具入門：你的第一個實際應用',
    slug: 'ai-tools-intro',
    summary: '從零開始認識 AI 工具，做出第一個可以對外展示的成果',
    upgradeLevel: '1',
    accessLevel: 'free',
    price: 0,
    order: 1,
  },
  {
    title: '[範例] 進階技能：從成果到可銷售的服務',
    slug: 'advanced-skills-to-service',
    summary: '把你的 AI 技能包裝成可以重複銷售的服務或數位商品',
    upgradeLevel: '2',
    accessLevel: 'paid',
    price: 2980,
    order: 2,
  },
  {
    title: '[範例] 完整系統：建立自動化的一人事業',
    slug: 'full-system-automation',
    summary: '用 AI Agent 建立不需要每天親自操作的收入系統',
    upgradeLevel: '3',
    accessLevel: 'paid',
    price: 9800,
    order: 3,
  },
]

export const seedPricingData = {
  title: '選擇你的升級路徑',
  subtitle: '每個階段都有明確的目標，做出真實可用的成果',
  tiers: [
    {
      level: 'l1' as const,
      label: 'Level 1',
      name: 'AI 基礎',
      price: '免費開始',
      priceNote: '→ 付費解鎖更多',
      features: [
        '[你的 L1 課程名稱]',
        '入門工具使用',
        'AI 基礎操作',
        '學員社群',
      ],
      ctaLabel: '搶先通知我開課',
      ctaHref: '#newsletter',
      highlighted: false,
    },
    {
      level: 'l2' as const,
      label: 'Level 2',
      name: '進階實戰',
      price: 'NT$2,980',
      priceNote: '一次付清',
      features: [
        '包含 L1 所有內容',
        '[你的 L2 課程主題]',
        '實戰上架流程',
        '定價與銷售策略',
        '真實案例分析',
      ],
      ctaLabel: '搶先通知我開課',
      ctaHref: '#newsletter',
      highlighted: true,
    },
    {
      level: 'l3' as const,
      label: 'Level 3',
      name: '全面升級',
      price: 'NT$9,800',
      priceNote: '一次付清',
      features: [
        '包含 L1 + L2 所有內容',
        '[你的 L3 課程主題]',
        'AI Agent 自動化工作流',
        '一人事業架構建立',
        '一對一教練諮詢（1 小時）',
      ],
      ctaLabel: '搶先通知我開課',
      ctaHref: '#newsletter',
      highlighted: false,
    },
  ],
}

export const seedLessons = [
  // ── BUILD L1 ─────────────────────────────────────────
  {
    title: '入門課程一：認識工具與基本操作',
    slug: 'intro-lesson-1-tools-basics',
    summary: '認識這個領域的核心 AI 工具，完成第一個上手練習，建立操作信心。',
    missionLabel: '入門任務',
    category: 'build' as const,
    upgradeLevel: '1' as const,
    level: 'beginner' as const,
    tools: ['ChatGPT', '[你使用的主要工具]'],
    durationMinutes: 30,
    outcome: '完成第一個可以對外展示的成果',
    accessLevel: 'free' as const,
    price: 0,
    order: 1,
  },
  {
    title: '入門課程二：第一個實際應用',
    slug: 'intro-lesson-2-first-application',
    summary: '把工具應用到真實情境，做出一個可以直接使用或展示的成品。',
    missionLabel: '實作任務',
    category: 'build' as const,
    upgradeLevel: '1' as const,
    level: 'beginner' as const,
    tools: ['ChatGPT', '[你使用的工具]'],
    durationMinutes: 40,
    outcome: '完成第一個實際應用成品，可直接展示',
    accessLevel: 'free' as const,
    price: 0,
    order: 2,
  },
  // ── BUILD L2 ─────────────────────────────────────────
  {
    title: '進階課程一：從零到第一個成果',
    slug: 'advanced-lesson-1-first-result',
    summary: '系統性地把技能轉化為可銷售的服務或商品，完成第一個可收款的成果。',
    missionLabel: '進階實戰任務',
    category: 'build' as const,
    upgradeLevel: '2' as const,
    level: 'easy' as const,
    tools: ['[你使用的工具]'],
    durationMinutes: 50,
    outcome: '完成一個可上架銷售的服務或商品',
    accessLevel: 'paid' as const,
    price: 490,
    order: 3,
  },
  {
    title: '進階課程二：優化與提升品質',
    slug: 'advanced-lesson-2-optimize-quality',
    summary: '提升輸出品質，學會系統性的定價與包裝方式，建立可重複的銷售流程。',
    missionLabel: '優化任務',
    category: 'build' as const,
    upgradeLevel: '2' as const,
    level: 'easy' as const,
    tools: ['[你使用的工具]'],
    durationMinutes: 45,
    outcome: '完成定價策略文件與銷售頁面',
    accessLevel: 'paid' as const,
    price: 490,
    order: 4,
  },
  // ── BUILD L3 ─────────────────────────────────────────
  {
    title: '完整課程：建立你的完整系統',
    slug: 'complete-lesson-full-system',
    summary: '用 AI Agent 建立自動化的一人事業系統，讓事業在你不在的時候也能持續運作。',
    missionLabel: '系統建構任務',
    category: 'build' as const,
    upgradeLevel: '3' as const,
    level: 'medium' as const,
    tools: ['Claude Code', '[你使用的工具]'],
    durationMinutes: 90,
    outcome: '一套自動化的事業系統，含內容產出與銷售流程',
    accessLevel: 'paid' as const,
    price: 2980,
    order: 5,
  },
  // ── SELL L1 ──────────────────────────────────────────
  {
    title: '銷售入門一：建立你的作品集',
    slug: 'sell-lesson-1-portfolio',
    summary: '建立一個能讓潛在客戶快速了解你的作品集，讓對的人主動找上你。',
    missionLabel: '作品集任務',
    category: 'sell' as const,
    upgradeLevel: '1' as const,
    level: 'beginner' as const,
    tools: ['Canva', 'ChatGPT'],
    durationMinutes: 40,
    outcome: '完成線上作品集，含作品展示與聯絡資訊',
    accessLevel: 'free' as const,
    price: 0,
    order: 1,
  },
  {
    title: '銷售入門二：個人品牌定位',
    slug: 'sell-lesson-2-brand-positioning',
    summary: '用 AI 協助你釐清個人品牌定位，回答「你是誰、你能幫誰、為什麼找你」。',
    missionLabel: '品牌定位任務',
    category: 'sell' as const,
    upgradeLevel: '1' as const,
    level: 'beginner' as const,
    tools: ['Claude', 'ChatGPT'],
    durationMinutes: 30,
    outcome: '完成個人品牌 One-Liner + 核心受眾定義',
    accessLevel: 'free' as const,
    price: 0,
    order: 2,
  },
]

export const seedFaqItems = [
  {
    question: '我沒有相關背景，可以學嗎？',
    answer: '可以。這個課程的設計前提就是你不需要專業背景。AI 工具大幅降低了入門門檻，重點是你有想法和行動力。',
  },
  {
    question: '課程是影片還是文字？',
    answer: '以影片為主，搭配可以直接操作的專案素材。每一課都有一個具體的完成物，不是只看不做。',
  },
  {
    question: '買了之後可以永久觀看嗎？',
    answer: '是的，購買後永久存取，未來更新內容也自動包含在內。',
  },
  {
    question: '付款系統什麼時候開放？',
    answer: '目前正在建置中，訂閱電子報後我們會第一時間通知你開放報名。',
  },
]
